source_set("common_client") {
  sources = [
    "common_client.cc",
    "common_client.h",
  ]

  deps = [
    "//base",
    "//extensions/common",
    "//extensions/common:core_api_provider",
    "//url",
  ]
}

source_set("browser_client") {
  sources = [
    "browser_client.cc",
    "browser_client.h",
    "content_browser_client_hooks.cc",
    "content_browser_client_hooks.h",
    "extension_loader.cc",
    "extension_loader.h",
    "extension_system.cc",
    "extension_system.h",
    "management.cc",
    "management.h",
  ]

  deps = [
    "//base",
    "//components/update_client",
    "//components/keyed_service/content",
    "//components/pref_registry",
    "//components/prefs",
    "//components/user_prefs",
    "//components/value_store",
    "//content/public/browser",
    "//crypto",
    "//extensions/browser",
    "//extensions/browser/updater:updater",
    "//extensions/common",
    "//extensions/common:mojom",
    "//mojo/public/cpp/bindings",
    "//services/network/public/mojom",
    "//services/network/public/cpp",
    "//url",
  ]
}

source_set("renderer_client") {
  sources = [
    "renderer_client.cc",
    "renderer_client.h",
  ]

  deps = [
    "//base",
    "//content/public/renderer",
    "//extensions/common",
    "//extensions/renderer",
  ]
}
