#!/usr/bin/env bash
# runtime-push.sh — Upload a pre-built Chromium runtime to Gitea releases.
#
# Creates a Gitea release tagged "runtime-<hash>" and uploads the platform
# tarball as a release asset. The hash is computed from the same inputs as
# runtime-pull.sh (chromium/.gclient, patches, bridge files), so push and
# pull are automatically keyed to the same build.
#
# Requirements:
#   - GITEA_TOKEN: personal access token for git.integrolabs.net
#     (needs "write:release" scope on the roctinam/carbonyl repo)
#   - jq: for parsing Gitea API responses
#   - curl: for API calls
#
# Note on file size: Gitea's default max upload size is configurable. If the
# runtime tarball (~75 MB) exceeds the server limit, increase
# `APP_MAX_ATTACHMENT_SIZE` in Gitea's `app.ini`, or use the R2 push path
# (the former AWS-based script is preserved below in the R2 section).
#
# Usage:
#   GITEA_TOKEN=<token> bash scripts/runtime-push.sh          # current platform
#   GITEA_TOKEN=<token> bash scripts/runtime-push.sh arm64    # arm64 platform

set -euo pipefail

export CARBONYL_ROOT=$(cd $(dirname -- "$0") && dirname -- $(pwd))

cd "$CARBONYL_ROOT"
source "scripts/env.sh"

: "${GITEA_TOKEN:?GITEA_TOKEN must be set (Gitea personal access token with write:release scope)}"

GITEA_BASE="${GITEA_BASE:-https://git.integrolabs.net}"
GITEA_REPO="roctinam/carbonyl"
GITEA_API="$GITEA_BASE/api/v1"

echo "Computing Chromium patches hash.."

hash=$(scripts/runtime-hash.sh)
triple=$(scripts/platform-triple.sh "${1:-}")
tag="runtime-$hash"

echo "Runtime hash:  $hash"
echo "Platform:      $triple"
echo "Release tag:   $tag"

# ── 1. Archive binaries ───────────────────────────────────────────────────────
cd build/pre-built

if [ ! -d "$triple" ]; then
    echo "ERROR: $PWD/$triple directory not found."
    echo "Build the runtime first with: bash scripts/docker-build.sh Default"
    exit 1
fi

echo "Archiving $triple.."
tar czf "$triple.tgz" "$triple"
echo "Archived to build/pre-built/$triple.tgz ($(du -sh "$triple.tgz" | cut -f1))"

cd "$CARBONYL_ROOT"

# ── 2. Create or find the Gitea release ──────────────────────────────────────
echo "Checking for existing Gitea release '$tag'.."

existing=$(curl -sf \
    -H "Authorization: token $GITEA_TOKEN" \
    "$GITEA_API/repos/$GITEA_REPO/releases/tags/$tag" 2>/dev/null || true)

if [ -n "$existing" ]; then
    release_id=$(echo "$existing" | jq '.id')
    echo "Release already exists (id=$release_id), reusing."
else
    echo "Creating Gitea release '$tag'.."
    release_id=$(curl -sf \
        -X POST "$GITEA_API/repos/$GITEA_REPO/releases" \
        -H "Authorization: token $GITEA_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{
          \"tag_name\": \"$tag\",
          \"name\": \"Runtime $hash\",
          \"body\": \"Pre-built Chromium runtime for Carbonyl (hash: $hash). Generated by scripts/runtime-push.sh.\",
          \"draft\": false,
          \"prerelease\": false
        }" | jq '.id')
    echo "Created release id=$release_id."
fi

# ── 3. Upload the tarball as a release asset ──────────────────────────────────
asset_path="build/pre-built/$triple.tgz"
asset_name="$triple.tgz"

echo "Uploading $asset_name to release $release_id.."

# Delete existing asset with same name if present (re-upload scenario)
existing_asset_id=$(curl -sf \
    -H "Authorization: token $GITEA_TOKEN" \
    "$GITEA_API/repos/$GITEA_REPO/releases/$release_id/assets" \
    | jq -r ".[] | select(.name == \"$asset_name\") | .id" 2>/dev/null || true)

if [ -n "$existing_asset_id" ]; then
    echo "Deleting existing asset $existing_asset_id ($asset_name).."
    curl -sf -X DELETE \
        -H "Authorization: token $GITEA_TOKEN" \
        "$GITEA_API/repos/$GITEA_REPO/releases/$release_id/assets/$existing_asset_id"
fi

curl -sf \
    -X POST "$GITEA_API/repos/$GITEA_REPO/releases/$release_id/assets" \
    -H "Authorization: token $GITEA_TOKEN" \
    -F "attachment=@$asset_path;filename=$asset_name" \
    > /dev/null

echo ""
echo "==> Upload complete."
echo "    $GITEA_BASE/$GITEA_REPO/releases/tag/$tag"
echo ""
echo "Verify pull works with:"
echo "    GITEA_BASE=$GITEA_BASE bash scripts/runtime-pull.sh ${1:-}"
