#!/usr/bin/env bash
# runtime-push.sh — Upload a pre-built Chromium runtime to Gitea releases.
#
# Creates a Gitea release tagged "runtime-<hash>" and uploads the platform
# tarball as a release asset. The hash is computed from the same inputs as
# runtime-pull.sh (chromium/.gclient, patches, bridge files), so push and
# pull are automatically keyed to the same build.
#
# Requirements:
#   - GITEA_TOKEN: personal access token for git.integrolabs.net
#     (needs "write:release" scope on the roctinam/carbonyl repo)
#   - jq: for parsing Gitea API responses
#   - curl: for API calls
#
# Note on file size: Gitea's default max upload size is configurable. If the
# runtime tarball (~75 MB) exceeds the server limit, increase
# `APP_MAX_ATTACHMENT_SIZE` in Gitea's `app.ini`, or use the R2 push path
# (the former AWS-based script is preserved below in the R2 section).
#
# Usage:
#   GITEA_TOKEN=<token> bash scripts/runtime-push.sh                     # headless, current cpu
#   GITEA_TOKEN=<token> bash scripts/runtime-push.sh arm64               # headless, arm64
#   GITEA_TOKEN=<token> bash scripts/runtime-push.sh --ozone=x11         # x11 variant
#   GITEA_TOKEN=<token> bash scripts/runtime-push.sh --ozone x11 amd64   # explicit cpu + variant
#
# CARBONYL_OZONE_TAG env var also works (e.g. for CI). The CLI flag
# wins when both are set.

set -euo pipefail

# Default ozone variant from env, overridden by --ozone=… below.
ozone="${CARBONYL_OZONE_TAG:-headless}"

positional=()
while [ $# -gt 0 ]; do
    case "$1" in
        --ozone=*) ozone="${1#--ozone=}" ;;
        --ozone)
            [ $# -ge 2 ] || { echo "ERROR: --ozone requires a value" >&2; exit 2; }
            ozone="$2"
            shift
            ;;
        -h|--help)
            sed -n '2,28p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        --) shift; while [ $# -gt 0 ]; do positional+=("$1"); shift; done; break ;;
        -*) echo "ERROR: unknown option: $1" >&2; exit 2 ;;
        *) positional+=("$1") ;;
    esac
    shift
done
set -- "${positional[@]+"${positional[@]}"}"

export CARBONYL_ROOT=$(cd $(dirname -- "$0") && dirname -- $(pwd))

cd "$CARBONYL_ROOT"
source "scripts/env.sh"

: "${GITEA_TOKEN:?GITEA_TOKEN must be set (Gitea personal access token with write:release scope)}"

GITEA_BASE="${GITEA_BASE:-https://git.integrolabs.net}"
GITEA_REPO="roctinam/carbonyl"
GITEA_API="$GITEA_BASE/api/v1"

echo "Computing Chromium patches hash.."

hash=$(scripts/runtime-hash.sh)
triple=$(scripts/platform-triple.sh "${1:-}")

# Tag-shape rule (mirror of runtime-pull.sh):
#   headless  → "runtime-<hash>"        (preserves historical tag)
#   any other → "runtime-<ozone>-<hash>"
case "$ozone" in
    headless) tag="runtime-$hash" ;;
    *)        tag="runtime-$ozone-$hash" ;;
esac

echo "Runtime hash:  $hash"
echo "Platform:      $triple"
echo "Ozone variant: $ozone"
echo "Release tag:   $tag"

# ── 1. Archive binaries ───────────────────────────────────────────────────────
cd build/pre-built

if [ ! -d "$triple" ]; then
    echo "ERROR: $PWD/$triple directory not found."
    echo "Build the runtime first with: bash scripts/docker-build.sh Default"
    exit 1
fi

echo "Archiving $triple.."
tar czf "$triple.tgz" "$triple"
echo "Archived to build/pre-built/$triple.tgz ($(du -sh "$triple.tgz" | cut -f1))"

cd "$CARBONYL_ROOT"

# ── 2. Create or find the Gitea release ──────────────────────────────────────
echo "Checking for existing Gitea release '$tag'.."

existing=$(curl -sf \
    -H "Authorization: token $GITEA_TOKEN" \
    "$GITEA_API/repos/$GITEA_REPO/releases/tags/$tag" 2>/dev/null || true)

if [ -n "$existing" ]; then
    release_id=$(echo "$existing" | jq '.id')
    echo "Release already exists (id=$release_id), reusing."
else
    echo "Creating Gitea release '$tag'.."
    resp=$(curl -s -w "\n__HTTP_CODE__%{http_code}" \
        -X POST "$GITEA_API/repos/$GITEA_REPO/releases" \
        -H "Authorization: token $GITEA_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{
          \"tag_name\": \"$tag\",
          \"name\": \"Runtime $ozone $hash\",
          \"body\": \"Pre-built Chromium runtime for Carbonyl (ozone: $ozone, hash: $hash). Generated by scripts/runtime-push.sh.\",
          \"draft\": false,
          \"prerelease\": false
        }")
    http_code="${resp##*__HTTP_CODE__}"
    body="${resp%__HTTP_CODE__*}"
    if [ "$http_code" != "201" ] && [ "$http_code" != "200" ]; then
        echo "ERROR: create-release HTTP $http_code"
        echo "response body: $body"
        exit 1
    fi
    release_id=$(echo "$body" | jq '.id')
    echo "Created release id=$release_id."
fi

# ── 3. Upload the tarball as a release asset ──────────────────────────────────
asset_path="build/pre-built/$triple.tgz"
asset_name="$triple.tgz"

echo "Uploading $asset_name to release $release_id.."

# Delete existing asset with same name if present (re-upload scenario)
existing_asset_id=$(curl -sf \
    -H "Authorization: token $GITEA_TOKEN" \
    "$GITEA_API/repos/$GITEA_REPO/releases/$release_id/assets" \
    | jq -r ".[] | select(.name == \"$asset_name\") | .id" 2>/dev/null || true)

if [ -n "$existing_asset_id" ]; then
    echo "Deleting existing asset $existing_asset_id ($asset_name).."
    curl -sf -X DELETE \
        -H "Authorization: token $GITEA_TOKEN" \
        "$GITEA_API/repos/$GITEA_REPO/releases/$release_id/assets/$existing_asset_id"
fi

curl -sf \
    -X POST "$GITEA_API/repos/$GITEA_REPO/releases/$release_id/assets" \
    -H "Authorization: token $GITEA_TOKEN" \
    -F "attachment=@$asset_path;filename=$asset_name" \
    > /dev/null

echo ""
echo "==> Upload complete."
echo "    $GITEA_BASE/$GITEA_REPO/releases/tag/$tag"
echo ""
echo "Verify pull works with:"
echo "    GITEA_BASE=$GITEA_BASE bash scripts/runtime-pull.sh ${1:-}"
